### ISSUE TITLE
关于flowL.yaml

### ISSUE THREAD

**Issue by lebron-2016** [gjhhust/YOLOFT#3]
尊敬的作者：

您好，

请问下图中的flowL.yaml在哪里？
![image](https://github.com/user-attachments/assets/b3126a18-0a50-45e7-bc10-b92f48b9bb9f)

感谢！！

**Comment by gjhhust** [comment]
这里https://github.com/gjhhust/YOLOFT/blob/main/config/yoloft/yoloft-L.yaml，flowFT是最初暂定的名称，最后全部改名为yoloft，我会修复该错误
