### ISSUE TITLE
Name 'stream' is not defined

### ISSUE THREAD

**Issue by lebron-2016** [gjhhust/YOLOFT#4]
尊敬的作者：

您好，

请问如何解决这里的警告和报错？
![image](https://github.com/user-attachments/assets/bc717d0d-f75a-41c5-a635-77441ce96d45)

感谢！！

**Comment by gjhhust** [comment]
谢谢，这个bug将会被修复.

**Comment by gjhhust** [comment]
我修复了bug，请重新拉去新的库后pip install -e .重新安装，接着重新下载权重文件进行测试

**Comment by gjhhust** [comment]
> 我修复了bug，请重新拉去新的库后pip install -e .重新安装，接着重新下载权重文件进行测试

run这个脚本https://github.com/gjhhust/YOLOFT/blob/main/tools/test_flowft.py

**Comment by lebron-2016** [comment]
> 我修复了bug，请重新拉去新的库后pip install -e .重新安装，接着重新下载权重文件进行测试

您好，我重新拉取并配置环境，还是有这个问题

**Comment by lebron-2016** [comment]
方便加微信沟通吗？（weixin：Clevelandss）

**Comment by gjhhust** [comment]
stream是一个模块

> > 我修复了bug，请重新拉去新的库后pip install -e .重新安装，接着重新下载权重文件进行测试
> 
> 您好，我重新拉取并配置环境
> 
> `python tools/train_flowft.py`
> 
> 还是有上述问题

我继续修复了该训练时的bug
