### ISSUE TITLE
Using the provided model file to test the picture has an error.

### ISSUE THREAD

**Issue by assertdebug** [gjhhust/YOLOFT#5]
![image](https://github.com/user-attachments/assets/26d579aa-b969-4a73-89f1-214fd4825f4d)
![image](https://github.com/user-attachments/assets/2f07e6f7-ce4b-464f-8961-0110f95b5a26)

**Comment by assertdebug** [comment]
Sorry , I forgot to specify the input size

**Comment by assertdebug** [comment]
I use the model file provided and cannot get the correct result

**Comment by assertdebug** [comment]
> I use the model file provided and cannot get the correct result
![image](https://github.com/user-attachments/assets/31b90f68-efc2-4e8a-bc23-a3c435109a06)

![image](https://github.com/user-attachments/assets/941d96cb-0b37-4fa1-98f1-6dbb1a9f7a44)

**Comment by gjhhust** [comment]
> > I use the model file provided and cannot get the correct result
> > ![image](https://private-user-images.githubusercontent.com/20460615/353403374-31b90f68-efc2-4e8a-bc23-a3c435109a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDQyNjgsIm5iZiI6MTcyMjM0Mzk2OCwicGF0aCI6Ii8yMDQ2MDYxNS8zNTM0MDMzNzQtMzFiOTBmNjgtZWZjMi00ZThhLWJjMjMtYTNjNDM1MTA5YTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEyNTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMWYzZDEzNDI4NjZlZWI1MjU4YTM4NGY2OTJlZmU5YzBiZjU2NGNjZDczZmMyNDk0YmM5YzQzMjQyNTk3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eKyKjzcj9YQEjTRKxK-pZ3u1GF_0buhB2-zcWIZfH70)
> 
> ![image](https://private-user-images.githubusercontent.com/20460615/353403524-941d96cb-0b37-4fa1-98f1-6dbb1a9f7a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDQyNjgsIm5iZiI6MTcyMjM0Mzk2OCwicGF0aCI6Ii8yMDQ2MDYxNS8zNTM0MDM1MjQtOTQxZDk2Y2ItMGIzNy00ZmExLTk4ZjEtNmRiYjFhOWY3YTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEyNTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYjUzNGExMjdjYWU0ODQ2ZDg1YzA5ODI5OWE4NzAxM2M0ODBmZjEzY2I5YzA2ODM3NTJkZGQ4NTI5MTNlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMYK7rYl3AOmuVtQXQcRRgyJi3Q49JBATmYfPjO62JY)

Currently does not support the direct use of yolo commands to reason, please use a script to get the results, and YOLOFT model is suitable for video reasoning, You need to use the build_stream_dataloader input model for video detection. You can refer to https://github.com/gjhhust/YOLOFT/blob/main/tools/test_flowft_show.py

**Comment by Yu-zhengbo** [comment]
> > > I use the model file provided and cannot get the correct result
> > > ![image](https://private-user-images.githubusercontent.com/20460615/353403374-31b90f68-efc2-4e8a-bc23-a3c435109a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDQyNjgsIm5iZiI6MTcyMjM0Mzk2OCwicGF0aCI6Ii8yMDQ2MDYxNS8zNTM0MDMzNzQtMzFiOTBmNjgtZWZjMi00ZThhLWJjMjMtYTNjNDM1MTA5YTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEyNTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMWYzZDEzNDI4NjZlZWI1MjU4YTM4NGY2OTJlZmU5YzBiZjU2NGNjZDczZmMyNDk0YmM5YzQzMjQyNTk3NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eKyKjzcj9YQEjTRKxK-pZ3u1GF_0buhB2-zcWIZfH70)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/20460615/353403524-941d96cb-0b37-4fa1-98f1-6dbb1a9f7a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDQyNjgsIm5iZiI6MTcyMjM0Mzk2OCwicGF0aCI6Ii8yMDQ2MDYxNS8zNTM0MDM1MjQtOTQxZDk2Y2ItMGIzNy00ZmExLTk4ZjEtNmRiYjFhOWY3YTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEyNTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYjUzNGExMjdjYWU0ODQ2ZDg1YzA5ODI5OWE4NzAxM2M0ODBmZjEzY2I5YzA2ODM3NTJkZGQ4NTI5MTNlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMYK7rYl3AOmuVtQXQcRRgyJi3Q49JBATmYfPjO62JY)
> 
> Currently does not support the direct use of yolo commands to reason, please use a script to get the results, and YOLOFT model is suitable for video reasoning, You need to use the build_stream_dataloader input model for video detection. You can refer to https://github.com/gjhhust/YOLOFT/blob/main/tools/test_flowft_show.py

你好，看了你写的代码，build_stream_dataloader好像返回的也是一帧一帧的图像，因为看了你的论文里面描述训练阶段是多帧输入，所以想请教一下是我理解错了吗

**Comment by gjhhust** [comment]
I wrote [predict scripts](https://github.com/gjhhust/YOLOFT/blob/main/tools/predict_yoloft.py) for images and videos, For more information, please read readme.md.

and Sorry only just noticed your question, the paper describes streaming input, i.e. only one image input at a point in time (consistent with real world acquisition of images)
