### ISSUE TITLE
Inference of Images

### ISSUE THREAD

**Issue by Yu-zhengbo** [gjhhust/YOLOFT#6]
#### I revisit the paper of YOLOFT, which is a video detection model. But I revist the codes, I find that I can not infer images with path only. 
1) I refer to the codes of "tools/test_flowft_show.py", which infer the image of video need annotations. 
2) So I try to export the weight of the model to onnx format, but I failed. 

So how can I use the model trained to infer an image or the images that match number of the least required of the model by path. Thanks a lot.

**Comment by gjhhust** [comment]
1. OK, Onxx转换失败的原因已经查明，是我们在参数传递中使用了字典，我们已经修复，涉及到模型参数传递，导致部分变更，使得原本的checkpoint无法使用，但是目前没有最够的训练资源进行修改后的训练得到新的可用检查点，因此目前暂时还不支持ONXX的转换版本，会在最近空闲出资源进行训练后发布新版本。
2. 目前我们仅支持测试集的推理，如果您想任何视频（mp4）或者图片文件夹都支持，我们将会更新该部分功能，如果您着急使用，可以进入[文件](https://github.com/gjhhust/YOLOFT/blob/main/ultralytics/models/yoloft/detect/predict.py)的第132行修改测试集推理结果保存位置直接保存，带来麻烦深感抱歉，我们会以最快的速度进行推出以上功能
![image](https://github.com/user-attachments/assets/c7dc1ae0-2d9c-4e1d-b1a6-4bc0aae62667)

**Comment by Yu-zhengbo** [comment]
> OK, The reason for the failure of Onxx conversion has been identified. It is that we used a dictionary in the parameter passing. We have fixed it. It involves the passing of model parameters, resulting in some changes, making the original checkpoint unusable. However, currently, there are not enough training resources to conduct the modified training to obtain a new available checkpoint. Therefore, the ONXX conversion version is not currently supported. A new version will be released after training with available resources in the near future. Currently, we only support inference of the test set. If you want support for any video (mp4) or image folder, we will update this part of the function. If you are in a hurry to use it, you can enter [File](https://github.com/gjhhust/YOLOFT/blob/main/ultralytics/models/yoloft/detect/predict.py) and modify the save location of the test set inference result on line 132 to save directly. We are deeply sorry for the inconvenience. We will launch the above functions at the fastest speed. ![image](https://private-user-images.githubusercontent.com/73829930/358577321-c7dc1ae0-2d9c-4e1d-b1a6-4bc0aae62667.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NjcyMDYsIm5iZiI6MTcyMzg2NjkwNiwicGF0aCI6Ii83MzgyOTkzMC8zNTg1NzczMjEtYzdkYzFhZTAtMmQ5Yy00ZTFkLWIxYTYtNGJjMGFhZTYyNjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDAzNTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YmE0MTgzMTk2OWQyZDNhYmExNTQyZDM3YTY3OGZmN2U4NjFjNDhhOGU5ODIzYzUyMjljYzg0NjBlMWZkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f7K_DqvI8qewgr33hJYJjzsginZOEF8tndpnIFw4_AQ)

Thanks for your reply!
I finish the video inference by generating a set of random labels, and use the "tools/test_flowft.py" to get the predict result. But it's so complex and inefficient. 
I never use the YOLOv8 or YOLOv5 of ultralytics, so if you can give me some information of the YOLOFT details, I may finish this function, and push the git branch to this repository.

**Comment by gjhhust** [comment]
I wrote [predict scripts](https://github.com/gjhhust/YOLOFT/blob/main/tools/predict_yoloft.py)  for images and videos, For more information, please read readme.md
